from widget.ConceptTable import ConceptTable
from widget.ConceptTree import ConceptTree
from widget.FileTable import FileTable
from widget.FileList import FileList
from widget.FileTab import FileTab
from widget.TextList import TextList
from widget.Desktop import Desktop
from widget.ConceptSearch import ConceptSearch
from widget.BackButton import BackButton